name: Test Release

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: "Who to greet?"
        required: true
        default: "enginc4n"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: enginc4n/custom-github-action@1.0 # organization/repo@tag
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
